version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '17:00'
      timezone: 'Europe/Berlin'
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope