version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: '/docker/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10