version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    open-pull-requests-limit: 15
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
    ignore:
      # Ignore updates for actions/checkout in Claude workflow files
      # Note: Dependabot doesn't support per-file ignores, so this ignores all
      # actions/checkout updates. Claude workflows should be updated manually.
      - dependency-name: 'actions/checkout'
        update-types: ['version-update:semver-major']
  - package-ecosystem: docker
    directory: '/docker/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
