version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    open-pull-requests-limit: 15
    exclude-paths:
      - 'tests/website/**'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
    exclude-paths:
      - '.github/workflows/claude*.yml'
  - package-ecosystem: docker
    directory: '/docker/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10
